default:
  before_script:
    - apt-get update --quiet --yes
    - apt-get install --quiet --yes flatpak flatpak-builder
    - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - flatpak install --noninteractive flathub org.freedesktop.Platform//21.08 org.freedesktop.Sdk//21.08 org.winehq.Wine//stable-21.08

build:
  stage: build
  script:
    - flatpak-builder --repo=artifact-repo build-dir com.gitlab.parcimonic.legendary.yml
    - flatpak build-bundle artifact-repo legendary.flatpak com.gitlab.parcimonic.legendary
  artifacts:
    paths:
      - legendary.flatpak
